#! /usr/bin/perl

use strict;

BEGIN {
  $^W = 1;  # Use warnings
  my $start_dir = '/Users/tomi/Projects/Bot-BasicBot';
  chdir($start_dir) or die "Cannot chdir to $start_dir: $!";
  @INC = 
    (
     '/sw/lib/perl5',
     '/sw/lib/perl5',
     '/System/Library/Perl/5.8.1/darwin-thread-multi-2level',
     '/System/Library/Perl/5.8.1',
     '/Library/Perl/5.8.1/darwin-thread-multi-2level',
     '/Library/Perl/5.8.1',
     '/Library/Perl',
     '/Network/Library/Perl/5.8.1/darwin-thread-multi-2level',
     '/Network/Library/Perl/5.8.1',
     '/Network/Library/Perl',
     '/Users/tomi/Projects/Bot-BasicBot'
    );
}

use Module::Build;

if (-e 'Build.PL' and not Module::Build->up_to_date("Build.PL", $0)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.
";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '/Users/tomi/Projects/Bot-BasicBot/_build',
  },
);

$build->dispatch;
